title: Everything EveryPlate
description: All about the EveryPlate and HelloFresh meal kits and their recipes!
theme: jekyll-theme-merlot
permalink: /:title
collections:
  spices:
    output: true
  units:
    output: false
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'spices'
    values:
      layout: 'spice'
